Repository chehl/chameleon, pull requests merged in 2023-02, with the labels that each got.

#2 Fixed two broken links to docs
  README.adoc
Labels: documentation

#3 Pipeline improvements
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/nightly-cve-scan.yml
  build.gradle
  gradlew
Labels: maintenance

#9 Added status badges in README.adoc
  README.adoc
Labels: documentation

#12 Clarified why we can (safely) disable CSRF
  src/main/java/cde/chameleon/config/WebSecurityConfig.java
Labels: documentation

#13 updated docker images
  localdeployment/docker-compose.yml
Labels: maintenance

#14 updated docker images
  .github/workflows/build.yml
  localdeployment/docker-compose.yml
  src/main/resources/application.yml
Labels: maintenance

#20 added PR decoration
  .github/workflows/build.yml
Labels: maintenance

#21 Recreate PR comment
  .github/workflows/build.yml
Labels: maintenance

#22 better pr decoration
  .github/workflows/build.yml
Labels: maintenance

#23 use publish-report action
  .github/workflows/build.yml
Labels: maintenance

#25 #24: switched to publish-report for nightly build.
  .github/workflows/build.yml
  .github/workflows/nightly-cve-scan.yml
  src/test/resources/owasp-dependency-check.xml
Labels: bug

#10 #1: Added docker compose v2 command to documentation
  docs/1_Architecture/1.3_Local_deployment.adoc
Labels: documentation
